### ISSUE TITLE
Keybase chat reply button has a smaller font-size than other buttons

### ISSUE THREAD

**Issue by sylveon** [Microsoft-community/Windows-theme#183]
![image](https://user-images.githubusercontent.com/6440374/31239461-25f845a2-a9cb-11e7-9ef0-6c6f98cb1e26.png)

I used the Firefox addon for that, not sure if Chrome addon reproduces, but linking it here anyways https://chrome.google.com/webstore/detail/keybase/ognfafcpbkogffpmmdglhbjboeojlefj

**Comment by Jasius** [comment]
Odd, that button doesn't even show up to me with the extension on Chrome.

**Comment by sylveon** [comment]
You need to login on keybase.io for the buttons to show up

**Comment by Jasius** [comment]
Didn't need to login, I just thought it's supposed to show up on threads rather than comments. Seeing it now.

**Comment by sylveon** [comment]
![gif](https://user-images.githubusercontent.com/6440374/31239843-85380826-a9cc-11e7-8e46-f85302c01585.gif)
Related

**Comment by Jasius** [comment]
Uh 
![image](https://user-images.githubusercontent.com/11031051/31239868-56da1c36-aa07-11e7-9f7c-f7ac7c83c508.png)
