### ISSUE TITLE
Filtering text overlays over subscribed subreddit list

### ISSUE THREAD

**Issue by TheTimeWalker** [Microsoft-community/Windows-theme#190]
![image](https://user-images.githubusercontent.com/8660693/31672120-f73c2d60-b35b-11e7-80d0-74a92446b9bb.png)

Only non-RES users are affected

**Comment by Jasius** [comment]
Must be FF bug.
________________________________

**Comment by TheTimeWalker** [comment]
![image](https://user-images.githubusercontent.com/8660693/31672906-0bf3e160-b35e-11e7-95f1-c0e758933914.png)
Same issue with Edge on Fall Creators Update though

**Comment by Jasius** [comment]
![image](https://user-images.githubusercontent.com/11031051/31677312-060bb22c-b373-11e7-8760-43bcc30130a4.png)
![image](https://user-images.githubusercontent.com/11031051/31677321-14907d00-b373-11e7-9d90-ee587b59d426.png)
Weird behavior on Chrome too.

**Comment by Martskin** [comment]
@TheTimeWalker 
I think I was able to address this issue in this PR:

https://github.com/Jasius/Windows-theme/pull/191

**Comment by Jasius** [comment]
Fixed in #191
