### ISSUE TITLE
Change "enjoying creators update" to "enjoying the Fall Creators Update"

### ISSUE THREAD

**Issue by jeffreymcclain** [Microsoft-community/Windows-theme#200]
https://github.com/Jasius/Windows-theme/blob/master/css/r-windows.css

https://github.com/Jasius/Windows-theme/blob/master/css/r-windows10.css

Picture of what I'm talking about: https://i.imgur.com/MMbPLyp.png

**Comment by Jasius** [comment]
@TheTimeWalker
