### ISSUE TITLE
/r/milking- new "reddit-logo" dosent replace old logo after complete set up

### ISSUE THREAD

**Issue by jm27904** [Microsoft-community/Windows-theme#208]
i have followed all of the set up steps to the best of my ability, and for some reason the stock reddit logo is appearing on the header to the left instead of the new "reddit-logo" icon. The old logo is covering both the Hot, and the New tabs. how do i solve this?

**Comment by Jasius** [comment]
Hey,

You're supposed to upload it here 
![image](https://user-images.githubusercontent.com/11031051/49472004-0795e380-f817-11e8-92c6-a16cccce3488.png)
https://old.reddit.com/r/milking/about/edit/

Let me know is that worked out for you. @jm27904

**Comment by jm27904** [comment]
gotcha thank you
