### ISSUE TITLE
Reddit premium advert obstructs submission buttons

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Windows-theme#209]

**Comment by Jasius** [comment]
Could you tackle this by any chance? https://mod.reddit.com/mail/perma/6duax

**Comment by TheTimeWalker** [comment]
I tried to replicate on Firefox but it seems to be fine on my end, investigating further...
![image](https://user-images.githubusercontent.com/8660693/50932754-dd16f600-1466-11e9-9684-6e0db6d3ce41.png)
