### ISSUE TITLE
Header snow is static on Firefox

### ISSUE THREAD

**Issue by Jasius** [Microsoft-community/Windows-theme#89]
This is how it works on all browsers with exception of Firefox https://video.twimg.com/tweet_video/CythFNwUsAAs_KN.mp4

On Firefox snow is still getting displayed but keyframes doesn't seem to work even with -moz- prefixes.

- [x] Prefixes are set
- [x] Exact same code works on all other browsers with and without prefixes

[Snow module](https://github.com/Jasius/Windows-theme/blob/master/scss/_snow.scss)

**Comment by LoganDark** [comment]
Why does it have to be animated on all browsers?

**Comment by LoganDark** [comment]
And also, are you sure you have a new version of firefox installed?

![](https://cloud.githubusercontent.com/assets/4723091/20938220/0d0ad53e-bb9f-11e6-99df-3903455e8d71.png)

**Comment by Jasius** [comment]
@LoganDark Because that's the intention, it just looks odd when it isn't animated, also i highly dislike inconsistencies.

It isn't applied to before, after elements, that doesn't really apply to this issue.

**Comment by LoganDark** [comment]
@Jasius Alright. Sorry if I misunderstood

**Comment by Jasius** [comment]
@LoganDark It's alright 😄
